version: '3.0'

services:
  nest:
    container_name: nest
    build: ./
    restart: always
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src

  postgres:
    container_name: postgres
    build: /database
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    command: ["postgres", "-c", "logging_collector=true", "-c", "log_statement=all"]
    volumes:
      - db-data_logs:/var/lib/postgresql/data
volumes:
  db-data_logs:

networks:
  node:
    driver: bridge
  postgres:
    driver: bridge

