version: '3.0'

services:
  nest:
    container_name: nest
    build: ./
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src

  postgres:
    container_name: postgres
    build: /database
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}
    volumes:
      - db-data:/var/lib/postgresql/data
      - db-logs:/var/log/postgresql.log

volumes:
  db-data:
  db-logs:

networks:
  node:
    driver: bridge
  postgres:
    driver: bridge

